### ISSUE TITLE
Failure to read PDF with image

### ISSUE THREAD

**Issue by nadenf** [pdf-rs/pdf#198]
Using this to extract data from images:  

```
      for (i, o) in images.iter().enumerate() {
            let img = match **o {
                XObject::Image(ref im) => im,
                _ => continue
            };

            let data = img.image_data(&resolver)?;

            let mut rgb_img: RgbImage = ImageBuffer::new(img.width, img.height);
            rgb_img.copy_from_slice(data.as_bytes());
```

Fails with this error:

```
thread 'indexer_pdf::tests::test_indexing' panicked at 'source slice length (5250) does not match destination slice length (15750)', src/indexer/document/src/indexer_pdf.rs:127:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/panicking.rs:67:14
   2: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
             at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/slice/mod.rs:3603:13
   3: core::slice::<impl [T]>::copy_from_slice
             at /rustc/903e279f468590fa3425f8aff7f3d61a5a873dbb/library/core/src/slice/mod.rs:3610:13
```

With this PDF: [Sample1.pdf](https://github.com/pdf-rs/pdf/files/12763521/Sample1.pdf)

**Comment by s3bk** [comment]
Not all images are RGB images.
You have to take a look at `color_space` to find out what it is.

**Comment by Its-Just-Nans** [comment]
Hello @s3bk 

Could it be possible for the pdf crate to haves functions to convert image_data to a png image for example ?
Or a subcrate `pdf-image` which could contains theses functions

```rs
for (name, &xobject_ref) in &resources.xobjects {
    let xobject = file
        .get(xobject_ref)
        .map_err(|e| AppError::from(e.to_string()))?;

    let XObject::Image(image) = &*xobject else {
        continue;
    };

    let png_buffer = pdf_image::pdf_image_to_png(&image, &resolver)?; // this function do the convertion
    // do stuff with the PNG
}
```

Thanks
