### ISSUE TITLE
Read pdf failed

### ISSUE THREAD

**Issue by zemelLeong** [pdf-rs/pdf#98]
I read a pdf by this code got an error.
```rust
#[cfg(test)]
mod pdf_test {
    use glob::glob;
    use pdf::file::File;

    macro_rules! file_path {
        ( $sub_dir:expr ) => { concat!("./src/test/common/", $sub_dir) }
    }

    macro_rules! run {
        ($e:expr) => (
            match $e {
                Ok(v) => v,
                Err(e) => {
                    e.trace();
                    panic!("{}", e);
                }
            }
        )
    }

    #[test]
    pub fn read_pages() {
        for entry in glob(file_path!("original.pdf")).expect("Failed to read glob pattern") {
            match entry {
                Ok(path) => {
                    println!("\n == Now testing `{}` ==", path.to_str().unwrap());
    
                    let path = path.to_str().unwrap();
                    let file = run!(File::<Vec<u8>>::open(path));
                    for i in 0 .. file.num_pages() {
                        println!("Read page {}", i);
                        let _ = file.get_page(i);
                    }
                }
                Err(e) => println!("{:?}", e)
            }
        }
    }
}
```

```
 == Now testing `src\test\common\original.pdf` ==
0: Try at C:\Users\11989\.cargo\registry\src\github.com-1ecc6299db9ec823\pdf-0.7.2\src\file.rs:277:23
1: Can't parse field root of struct RcRef < Catalog >.
2: Try at C:\Users\11989\.cargo\registry\src\github.com-1ecc6299db9ec823\pdf-0.7.2\src\file.rs:94:19
3: Can't parse field names of struct Option < RcRef < NameDictionary > >.
4: Expected primitive Reference, found primive Dictionary instead.
thread 'test::pdf_test::pdf_test::read_pages' panicked at 'Try at C:\Users\11989\.cargo\registry\src\github.com-1ecc6299db9ec823\pdf-0.7.2\src\file.rs:277:23', src\test\pdf_test.rs:33:32
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2\/library\std\src\panicking.rs:515
   1: std::panicking::begin_panic_fmt
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2\/library\std\src\panicking.rs:457
   2: document_manager::test::pdf_test::pdf_test::read_pages
             at .\src\test\pdf_test.rs:33
   3: document_manager::test::pdf_test::pdf_test::read_pages::{{closure}}
             at .\src\test\pdf_test.rs:23
   4: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2\library\core\src\ops\function.rs:227
   5: core::ops::function::FnOnce::call_once
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test::pdf_test::pdf_test::read_pages ... FAILED

failures:

failures:
    test::pdf_test::pdf_test::read_pages
```

I rewrite this file by Python PyPDF2 then can read it successfully. But the rewritten file becomes smaller.
```python
from PyPDF2 import PdfFileReader, PdfFileWriter

pdf_input = PdfFileReader(open("talkiin.pdf", 'rb'))
page_count = pdf_input.getNumPages()

pdf_output = PdfFileWriter()
for i in range(page_count):
    page = pdf_input.getPage(i)
    pdf_output.addPage(page)

pdf_output.write(open("./splitted.pdf".format(i), 'wb'))

```
![image](https://user-images.githubusercontent.com/26835087/128216805-431d0088-7ea0-4afc-8af0-d76f8c3030fa.png)

I'm sorry I can't provide this document.

**Comment by zemelLeong** [comment]
The problem is the same as [https://github.com/pdf-rs/pdf/issues/97](https://github.com/pdf-rs/pdf/issues/97).
How can I get the newest version?
![image](https://user-images.githubusercontent.com/26835087/128279614-f295bab1-3509-4786-9494-65d9bf54f80d.png)

**Comment by zemelLeong** [comment]
![image](https://user-images.githubusercontent.com/26835087/128280507-1bed0559-2ac4-4c43-9ee2-81af08389e8e.png)

**Comment by s3bk** [comment]
Yes, a new release should happen in the new future.
